services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=auth_service
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - CONSUL_FOLDER=${CONSUL_FOLDER}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - RUN_MODE=${RUN_MODE}
    depends_on:
      - postgres
    networks:
      - booking-net

  postgres:
    image: postgres:17.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_service
    networks:
      - booking-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  booking-net:
    external: true
    name: booking-net

volumes:
  postgres-data:
